#!/usr/bin/env perl

=begin License

The MIT License (MIT)

Copyright (c) 2014 Jason White <jdwhite@menelos.com>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=end License
=cut

#
# osx-srvrcache_monitor - report OS X Server caching server status and usage.
#
# Jason White <jdwhite@menelos.com>
# 8-Mar-2014 (first release)
#
# Install in $XYMONCLIENTHOME/client/ext/.
# Modify $XYMONCLIENTHOME/etc/clientlaunch.cfg and add this block:
#
# # OS X Server caching server
# [osx_srvrcache_mon]
#	  ENABLED
#	  ENVFILE $XYMONCLIENTHOME/etc/xymonclient.cfg
#	  CMD $XYMONCLIENTHOME/ext/osx-srvrcache_monitor
#	  LOGFILE $XYMONCLIENTHOME/logs/osx-srvrcache_monitor.log
#	  INTERVAL 10m
#
# serveradmin must run as root. Modify /etc/sudoers as follows:
#
#   * Add the following line to the bottom of the config file to allow
#     user xymon to execute the serveradmin command without a password:
#
#        xymon   ALL= NOPASSWD: /Applications/Server.app/Contents/ServerRoot/usr/sbin/serveradmin
#

use strict;
use warnings;

## Globals ##
$main::TESTNAME = 'srvrcache';
$main::COLOR    = "clear";	# uncertain by default
$main::DATA     = "";
$main::MACHINE  = $ENV{MACHINE};

$main::SERVERADMIN =
	"/Applications/Server.app/Contents/ServerRoot/usr/sbin/serveradmin";

my(@details);
open(STATUS,"sudo ${main::SERVERADMIN} fullstatus caching |") || do {
	$main::COLOR = "red";
	$main::status = "Error getting cache status - $!";
};

#
# Read status information and process.
#
%main::stats = ();
@main::cachedetails = ();
while(<STATUS>) {
	s/^caching://;
	chomp;
	if (/^CacheDetails:_array_index:(\d+):(.+)\s=\s(.+)$/io) {
		#
		# These are the caching details broken down by data type.
		#
		my($element, $key, $val) = ($1, $2, $3);
		$val =~ s/\"//go;
		$main::cachedetails[$element]{$key} = $val;
	}
	else {
		#
		# Metadata regarding the cache (status, size, utilization, etc.)
		#
		my($key, $val) = split(/ = /, $_);
		$val =~ s/\"//go;
		$main::stats{$key} = $val;
	}
}
close(STATUS);

#
# Check overall state.
#
if ($main::stats{state} eq "RUNNING") {
	$main::COLOR = "green";
	$main::status = $main::stats{state};

	$main::DATA .= sprintf("%15s: %sM\n%15s: %sM (%0.1f%%)\n",
		"Cache Size", int($main::stats{CacheLimit}/1024/1024),
		"Cache Used", int($main::stats{CacheUsed}/1024/1024),
		($main::stats{CacheUsed} / $main::stats{CacheLimit}) * 100
	);
}
elsif ($main::stats{state} eq "STOPPED") {
	# A stopped caching server doesn't provide cache size info.
	$main::COLOR = "yellow";
	$main::status = $main::stats{state};

	$main::DATA .= sprintf("%15s: %sM\n",
		"Cache Used", int($main::stats{CacheUsed}/1024/1024));
}
else {
	$main::COLOR = "red"; # unknown state
	$main::status = $main::stats{state};
}

$main::DATA .= "\n";

#
# Display usage by type.
#
foreach my $hash (@main::cachedetails) {
	$main::DATA .= sprintf("%15s: %sM\n", 
		$hash->{LocalizedType}, int($hash->{BytesUsed}/1024/1024));
}

print $main::DATA,"\n";

##
## Generate status report.
##

# STATUS - Canonical status of test and its lifetime: status[+LIFETIME]
#$STATUS = "status+25h ${main::MACHINE}.${main::TESTNAME} ${main::COLOR}";
$main::STATUS = "status ${main::MACHINE}.${main::TESTNAME} ${main::COLOR}";

# SUMMARY - datestamp and summary of the test.
$main::SUMMARY = scalar(localtime(time))." - ${main::TESTNAME}: $main::status";

# MESSAGE - status, summary, diagnostic data combined.
$main::MESSAGE = "${main::STATUS} ${main::SUMMARY}\n\n${main::DATA}";

##
## Send to Xymon or to stdout if run interactively.
##
if (defined($ENV{XYMON})) {
	# "at" sign as argument means "read message data from stdin".
	# DON'T USE A DASH AS THE xymon USAGE MESSAGE SHOWS ELSE ONLY
	# THE SUMMARY INFORMATION IS DISPLAYED AND NONE OF $main::DATA.
	# THE MANPAGE USAGE OF "@" IS CORRECT.
	open(XYMON, "| $ENV{XYMON} $ENV{XYMSRV} @") || do {
	print "Error invoking $ENV{XYMON} $ENV{XYMSRV} @ - $!";
		exit;
	};
	select(XYMON);
}
else {
	print STDERR "*** Not invoked by Xymon; sending to stdout ***\n\n";
}

print $main::MESSAGE;
close(XYMON);

exit;

__END__

# Server running normally.
caching:Active = yes
caching:state = "RUNNING"
caching:CacheUsed = 1812413411
caching:Port = 51332
caching:TotalBytesRequested = 0
caching:RegistrationStatus = 1
caching:CacheLimit = 78503358335
caching:CacheFree = 76690944924
caching:Peers = _empty_array
caching:TotalBytesFromPeers = 0
caching:StartupStatus = "OK"
caching:TotalBytesFromOrigin = 0
caching:CacheStatus = "OK"
caching:TotalBytesReturned = 0
caching:CacheDetails:_array_index:0:BytesUsed = 1583108743
caching:CacheDetails:_array_index:0:LocalizedType = "Mac Software"
caching:CacheDetails:_array_index:0:MediaType = "Mac Software"
caching:CacheDetails:_array_index:0:Language = "en"
caching:CacheDetails:_array_index:1:BytesUsed = 161476803
caching:CacheDetails:_array_index:1:LocalizedType = "iOS Software"
caching:CacheDetails:_array_index:1:MediaType = "iOS Software"
caching:CacheDetails:_array_index:1:Language = "en"
caching:CacheDetails:_array_index:2:BytesUsed = 1726668
caching:CacheDetails:_array_index:2:LocalizedType = "Books"
caching:CacheDetails:_array_index:2:MediaType = "Books"
caching:CacheDetails:_array_index:2:Language = "en"
caching:CacheDetails:_array_index:3:BytesUsed = 0
caching:CacheDetails:_array_index:3:LocalizedType = "Movies"
caching:CacheDetails:_array_index:3:MediaType = "Movies"
caching:CacheDetails:_array_index:3:Language = "en"
caching:CacheDetails:_array_index:4:BytesUsed = 0
caching:CacheDetails:_array_index:4:LocalizedType = "Music"
caching:CacheDetails:_array_index:4:MediaType = "Music"
caching:CacheDetails:_array_index:4:Language = "en"
caching:CacheDetails:_array_index:5:BytesUsed = 66101197
caching:CacheDetails:_array_index:5:LocalizedType = "Other"
caching:CacheDetails:_array_index:5:MediaType = "Other"
caching:CacheDetails:_array_index:5:Language = "en"


# Sever in stopped state.
caching:CacheStatus = "OK"
caching:CacheDetails:_array_index:0:BytesUsed = 1583108743
caching:CacheDetails:_array_index:0:LocalizedType = "Mac Apps"
caching:CacheDetails:_array_index:0:MediaType = "Mac Apps"
caching:CacheDetails:_array_index:0:Language = "en"
caching:CacheDetails:_array_index:1:BytesUsed = 161476803
caching:CacheDetails:_array_index:1:LocalizedType = "iOS Apps"
caching:CacheDetails:_array_index:1:MediaType = "iOS Apps"
caching:CacheDetails:_array_index:1:Language = "en"
caching:CacheDetails:_array_index:2:BytesUsed = 1726668
caching:CacheDetails:_array_index:2:LocalizedType = "Books"
caching:CacheDetails:_array_index:2:MediaType = "Books"
caching:CacheDetails:_array_index:2:Language = "en"
caching:CacheDetails:_array_index:3:BytesUsed = 0
caching:CacheDetails:_array_index:3:LocalizedType = "Movies"
caching:CacheDetails:_array_index:3:MediaType = "Movies"
caching:CacheDetails:_array_index:3:Language = "en"
caching:CacheDetails:_array_index:4:BytesUsed = 0
caching:CacheDetails:_array_index:4:LocalizedType = "Music"
caching:CacheDetails:_array_index:4:MediaType = "Music"
caching:CacheDetails:_array_index:4:Language = "en"
caching:CacheDetails:_array_index:5:BytesUsed = 66101197
caching:CacheDetails:_array_index:5:LocalizedType = "Other"
caching:CacheDetails:_array_index:5:MediaType = "Other"
caching:CacheDetails:_array_index:5:Language = "en"
caching:state = "STOPPED"
caching:CacheUsed = 1812413411
